### ISSUE TITLE
Left menu not working under ReadTheDocs Themes

### ISSUE THREAD

**Issue by pajaro1966** [Rj40x40/mkdocs-import-statement-plugin#1]
Thanks a lot for a great plugin. It's working for me and I can import .md files into .md files. But for some reason the TOC on the left menu doesn't work properly, as you can see in the screen shot:

![image](https://github.com/Rj40x40/mkdocs-import-statement-plugin/assets/3808217/2d9ac658-9a3e-4eca-98cf-77cbb7cabda8)

There is only the first header of the .md file ("1.1. Condicionales"), but the following ones are not visible ("Condicional final",  …). I don't know if the plugin import-statement is confusing the headers of the mother .md files with those of the embedded .md files.

This is the beginning of my code in the importing file:

```
---
title: "GRAMÁTICA"
---

# Gramática

## 1.1. Condicionales

### 1.1.1. [Condicionales finales](grammar/final_condicional.md): ‘por si’

@import "grammar/final_condicional.md"

## 1.2. Finales

### 1.2.1. [Finales condicionales](grammar/final_condicional.md) ‘por si’

@import "grammar/final_condicional.md"

## 1.3. Modo

```

This is the content of my mkdocs.yml file:

```
site_name: Homero
site_url: https://pajaro1966.github.io/My_Mk_Docs/
plugins:
  - search
  - import-statement
extra_javascript:
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
theme:
  name: readthedocs
  features:
    - search.highlight
nav:
  - 'Home': 'index.md'
  - Comentarios: 'Comentarios/Homer_Seymour.md'
  - Diccionario: 'diccionarios.html'
  - Geografía: 'geografia.md'
  - Gramática: 'gramatica.md'
  - Métrica: 'metric_Homer.md'
  - Morfología flexiva: 'https://pajaro1966.github.io/Paradigmas_Griegos/'
  - Nombres y epítetos: 'nombres_Homer.md'
  - Notas: 'notas.md'
  - Referencias: 'referencias.md'
  - Términos homéricos: 'terminos_Homer.md'
  - 'Textos': 
    - 'Ilíada': 'textos.md'
    - 'Odisea': 'text_Odisea.md'
  - Traducciones: 'traduc_ES.md'
  - Verbos: 'verbo.md'

```

Thanks in advance for your eventual help and for creating this plugin.
